### ISSUE TITLE
idea: need a way to shut down the processes cleanly

### ISSUE THREAD

**Issue by ghost** [sako0938/LND-iot-app-launcher#2]
Here's the issue I'm having with ltcd.  (Presumably would be a similar issue with other services too).  Reboot the service and when it comes back up, ltcd complains: ```[INF] BCDB: Detected unclean shutdown - Repairing...```

https://www.balena.io/docs/learn/manage/actions/#restart-application

Perhaps there is some way of detecting a SIGTERM and reacting appropriately by calling 'ltcctl stop' to do a clean shutdown of ltcd.

**Comment by kornpow** [comment]
How are you rebooting the service? Are you using the Balena UI? Why are you rebooting if I might ask?

**Comment by ghost** [comment]
Yes, from the Balena UI.  So far I've needed to shut down a few times in order to move the SSD over to another machine and copy data onto it.  I could of course shut down things manually from the command line but it would be nice to be able to do it with the click of a button..

**Comment by kornpow** [comment]
https://www.balena.io/docs/reference/base-images/base-images/#how-the-images-work-at-runtime
"At the end of a container's lifecycle, when a request to container restart, reboot or shutdown is sent to the supervisor, the balenaEngine will send a SIGTERM (signal 15) to the containers, and 10 seconds later it will issue a SIGKILL if the container is still running. This timeout can also be configured via the stop_grace_period in your docker-compose.yml."

**Comment by ghost** [comment]
looks like we could use the ```trap``` command in the start script.

https://unix.stackexchange.com/questions/313644/execute-command-or-function-when-sigint-or-sigterm-is-send-to-the-parent-script

**Comment by ghost** [comment]
whew, got it working!  had to switch to using "ENTRYPOINT" instead of "CMD" in dockerfile in order to receive the signals in the script.
